config/routes.rb
Rails.application.routes.draw do

  root :to => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :users do
    resources :posts
  end

  get 'posts/all', :to => 'posts#all'  
  get 'posts/north_america', :to => 'posts#north_america'
  get 'posts/south_america', :to => 'posts#south_america'
  get 'posts/europe', :to => 'posts#europe'
  get 'posts/asia', :to => 'posts#asia'
  get 'posts/australia', :to => 'posts#australia'
  get 'posts/africa', :to => 'posts#africa'
  get 'posts/antarctica', :to => 'posts#antarctica'

  # delete '/sessions' => 'sessions#destroy'

end
 

app/models/post.rb
class Post

  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  has_mongoid_attached_file :photo_one,
    :styles => {
    :small => "200x200",
    :medium => "350x350",
    :large => "500x500"
  }

  has_mongoid_attached_file :photo_two,
    :styles => {
    :small => "200x200",
    :medium => "350x350",
    :large => "500x500"
  }

  has_mongoid_attached_file :photo_three,
    :styles => {
    :small => "200x200",
    :medium => "350x350",
    :large => "500x500"
  }

  has_mongoid_attached_file :photo_four,
    :styles => {
    :small => "200x200",
    :medium => "350x350",
    :large => "500x500"
  }

  field :rating, type: Integer
  field :city, type: String
  field :country, type: String
  field :continent, type: String
  field :hostel, type: String
  field :hostel_rating, type: Integer
  field :hostel_review, type: String
  field :eatery, type: String
  field :eatery_dish, type: String
  field :sight_one, type: String
  field :sight_two, type: String
  field :sight_three, type: String
  field :safety_tips, type: String
  field :overall, type: String
  field :latitude, type: Float
  field :longitude, type: Float
  field :user_id, type: String

  validates_attachment_content_type :photo_one, :photo_two, :photo_three, :photo_four, content_type: /\Aimage\/.*\Z/

  belongs_to :user

end

app/models/user.rb
require 'bcrypt'

class User

  include Mongoid::Document
  include Mongoid::Paperclip

  validates :first, presence: true
  validates :last, presence: true
  validates :email, presence: true
  validates :email, format: { with: /@/,
    message: "not a valid email" }
  validates :password, presence: true
  validates :password, length: { minimum: 8, 
    message: "password must be at least 8 characters" }

  field :first, type: String
  field :last, type: String
  field :email, type: String
  field :password_digest, type: String
  field :latitude, type: Float
  field :longitude, type: Float

  has_mongoid_attached_file :avatar,
    :styles => {
    :small => "150x150",
    :medium => "300x300"
  }

  # :thumb => "100x100#",
  # :small => "150x150>",
  # :medium => "200X200"

  attr_reader :password

	# validates_presence_of :first, :message => "Enter your first name"

	def password=(new_password)
		self.password_digest = BCrypt::Password.create(new_password)
	end

	def authenticate(test_password)
		if test_password && BCrypt::Password.new(self.password_digest) == test_password
			self
		else
			false
		end
	end

	 validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

   has_many :posts

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :find_user, :only => [:new, :create, :index, :edit, :update, :destroy]

  # before_filter :user_validation, :only => [:new, :create, :edit, :update, :destroy]

  def all
    @posts = Post.all
    @users = User.all
  end

  def north_america
    @posts = Post.where(continent: "NAX")
    @users = User.all
  end

  def south_america
    @posts = Post.where(continent: "SAX")
    @users = User.all
  end

  def europe
    @posts = Post.where(continent: "EUX")
    @users = User.all
  end

  def asia
    @posts = Post.where(continent: "ASX")
    @users = User.all
  end

  def australia
    @posts = Post.where(continent: "AUX")
    @users = User.all
  end

  def africa
    @posts = Post.where(continent: "AFX")
    @users = User.all
  end

  def antarctica
    @posts = Post.where(continent: "ANX")
    @users = User.all
  end

  def new
    @post = @user.posts.new
    user_validation
  end

  def index
    @posts = @user.posts.all
  end

  def show
    @post = Post.find(params[:id])
    @user = User.where(id: @post.user_id).first
  end

  def create
    @post = @user.posts.create(post_params)
    @post.user_id = @user.id
    if @post.save
    	redirect_to user_path(@user)
    else
    	render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    user_validation
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to user_posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    user_validation
    @post.destroy
    redirect_to posts_path
  end

  def find_user
    @user = User.find(params[:user_id])

    if @user == false
      redirect_to root_path 
    end
  end

  def post_params
    params.require(:post).permit(:id, :rating, :city, :country, :continent, :hostel, :hostel_rating, :hostel_review, :eatery, :eatery_dish, :sight_one, :sight_two, :sight_three, :overall, :safety_tips, :latitude, :longitude, :photo_one, :photo_two, :photo_three, :photo_four, :user_id)
  end

  def user_validation
    if @post.user_id != current_user.id || current_user == nil
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # flash.clear
  end

  def create
    flash.clear
  	begin
  	  user = User.find_by({email: params[:session][:email]})
    rescue
  	  flash[:error] = "Email Not Found!"
    end

    if user && user.authenticate(params[:session][:password])
  	  log_in(user)
  	  redirect_to user_path(current_user)
    else
  	  flash[:error] ||= "Try Again!"
  	  redirect_to root_path
    end
  end

  def destroy
  	log_out
  	redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    user_validation
    @post_count = @user.posts.count
  end

  def create 
    @user = User.new(params.require(:user).permit(:first, :last, :email, :password))
      if @user.save
        log_in(@user)
        redirect_to user_path(@user)
      else
        render 'new'
      end 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params.require(:user).permit(:first, :last, :email, :avatar))
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def user_validation
    if @user.id != current_user.id || current_user == nil
      redirect_to root_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    cookies.permanent[:user_id] = user.id
    @current_user = user
  end

  def log_out
    cookies.delete(:user_id)
  end

  def logged_in?
    current_user ? true : false
  end

  # def current_user
  #   if logged_in?
  #     @current_user ||= User.find(cookies[:cookie_id])
  #   else
  #     nil
  #   end
  # end

  def current_user
    # Test if cookie exists
    if cookies[:user_id] 
      # Find user in DB only if @current_user does not exist
      @current_user ||= User.find(cookies[:user_id])
    else
      # Set to nil only if @current_user does not exist
      @current_user ||= nil
    end
  end

  def current_user=(user)
    @current_user = user 
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BPT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,600' rel='stylesheet' type='text/css'>
</head>
<body>

<%= flash[:error] %>

<%= yield %>

</body>
</html>

app/views/posts/africa.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

  <div id="continent-list-div">
    <div class="continent"><%= link_to "All", posts_all_path %></div>
    <div class="continent"><%= link_to "Australia", posts_australia_path %></div>
    <div class="continent"><%= link_to "Europe", posts_europe_path %></div>
    <div class="continent"><%= link_to "North America", posts_north_america_path %></div>
    <div class="continent"><%= link_to "Asia", posts_asia_path %></div>
    <div class="continent"><%= link_to "South America", posts_south_america_path %></div>
    <div class="continent-active"><%= link_to "Africa", posts_africa_path %></div>
    <div class="continent"><%= link_to "Antarctica", posts_antarctica_path %></div>
  </div>

  <div class="p-a-div">
    <% @posts.each do |p| %>
      <%= link_to user_post_path(@users, p) do %>
        <div class="p-a-entry-div">
          <div class="p-a-entry">
            <%= image_tag p.photo_one.url(:medium), class: 'p-a-photo-one' %>
              <%= image_tag p.photo_two.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_three.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_four.url(:medium), class: 'p-a-photo-234' %>
            <p class="p-a-city"><%= p.city %></p>
            <p class="p-a-country"><%= p.country %></p>
            <p class="p-a-rating"><%= p.rating %> / 5</p>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>

</body>

app/views/posts/all.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

  <div id="continent-list-div">
    <div class="continent-active"><%= link_to "All", posts_all_path %></div>
    <div class="continent"><%= link_to "Australia", posts_australia_path %></div>
    <div class="continent"><%= link_to "Europe", posts_europe_path %></div>
    <div class="continent"><%= link_to "North America", posts_north_america_path %></div>
    <div class="continent"><%= link_to "Asia", posts_asia_path %></div>
    <div class="continent"><%= link_to "South America", posts_south_america_path %></div>
    <div class="continent"><%= link_to "Africa", posts_africa_path %></div>
    <div class="continent"><%= link_to "Antarctica", posts_antarctica_path %></div>
  </div>

  <div class="p-a-div">
    <% @posts.each do |p| %>
      <%= link_to user_post_path(@users, p) do %>
        <div class="p-a-entry-div">
          <div class="p-a-entry">
            <%= image_tag p.photo_one.url(:medium), class: 'p-a-photo-one' %>
              <%= image_tag p.photo_two.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_three.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_four.url(:medium), class: 'p-a-photo-234' %>
            <p class="p-a-city"><%= p.city %></p>
            <p class="p-a-country"><%= p.country %></p>
            <p class="p-a-rating"><%= p.rating %> / 5</p>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>

</body>

app/views/posts/antarctica.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

  <div id="continent-list-div">
    <div class="continent"><%= link_to "All", posts_all_path %></div>
    <div class="continent"><%= link_to "Australia", posts_australia_path %></div>
    <div class="continent"><%= link_to "Europe", posts_europe_path %></div>
    <div class="continent"><%= link_to "North America", posts_north_america_path %></div>
    <div class="continent"><%= link_to "Asia", posts_asia_path %></div>
    <div class="continent"><%= link_to "South America", posts_south_america_path %></div>
    <div class="continent"><%= link_to "Africa", posts_africa_path %></div>
    <div class="continent-active"><%= link_to "Antarctica", posts_antarctica_path %></div>
  </div>

  <div class="p-a-div">
    <% @posts.each do |p| %>
      <%= link_to user_post_path(@users, p) do %>
        <div class="p-a-entry-div">
          <div class="p-a-entry">
            <%= image_tag p.photo_one.url(:medium), class: 'p-a-photo-one' %>
              <%= image_tag p.photo_two.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_three.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_four.url(:medium), class: 'p-a-photo-234' %>
            <p class="p-a-city"><%= p.city %></p>
            <p class="p-a-country"><%= p.country %></p>
            <p class="p-a-rating"><%= p.rating %> / 5</p>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>

</body>

app/views/posts/asia.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

  <div id="continent-list-div">
    <div class="continent"><%= link_to "All", posts_all_path %></div>
    <div class="continent"><%= link_to "Australia", posts_australia_path %></div>
    <div class="continent"><%= link_to "Europe", posts_europe_path %></div>
    <div class="continent"><%= link_to "North America", posts_north_america_path %></div>
    <div class="continent-active"><%= link_to "Asia", posts_asia_path %></div>
    <div class="continent"><%= link_to "South America", posts_south_america_path %></div>
    <div class="continent"><%= link_to "Africa", posts_africa_path %></div>
    <div class="continent"><%= link_to "Antarctica", posts_antarctica_path %></div>
  </div>

  <div class="p-a-div">
    <% @posts.each do |p| %>
      <%= link_to user_post_path(@users, p) do %>
        <div class="p-a-entry-div">
          <div class="p-a-entry">
            <%= image_tag p.photo_one.url(:medium), class: 'p-a-photo-one' %>
              <%= image_tag p.photo_two.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_three.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_four.url(:medium), class: 'p-a-photo-234' %>
            <p class="p-a-city"><%= p.city %></p>
            <p class="p-a-country"><%= p.country %></p>
            <p class="p-a-rating"><%= p.rating %> / 5</p>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>

</body>

app/views/posts/australia.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

  <div id="continent-list-div">
    <div class="continent"><%= link_to "All", posts_all_path %></div>
    <div class="continent-active"><%= link_to "Australia", posts_australia_path %></div>
    <div class="continent"><%= link_to "Europe", posts_europe_path %></div>
    <div class="continent"><%= link_to "North America", posts_north_america_path %></div>
    <div class="continent"><%= link_to "Asia", posts_asia_path %></div>
    <div class="continent"><%= link_to "South America", posts_south_america_path %></div>
    <div class="continent"><%= link_to "Africa", posts_africa_path %></div>
    <div class="continent"><%= link_to "Antarctica", posts_antarctica_path %></div>
  </div>

  <div class="p-a-div">
    <% @posts.each do |p| %>
      <%= link_to user_post_path(@users, p) do %>
        <div class="p-a-entry-div">
          <div class="p-a-entry">
            <%= image_tag p.photo_one.url(:medium), class: 'p-a-photo-one' %>
              <%= image_tag p.photo_two.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_three.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_four.url(:medium), class: 'p-a-photo-234' %>
            <p class="p-a-city"><%= p.city %></p>
            <p class="p-a-country"><%= p.country %></p>
            <p class="p-a-rating"><%= p.rating %> / 5</p>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>

</body>

app/views/posts/europe.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

  <div id="continent-list-div">
    <div class="continent"><%= link_to "All", posts_all_path %></div>
    <div class="continent"><%= link_to "Australia", posts_australia_path %></div>
    <div class="continent-active"><%= link_to "Europe", posts_europe_path %></div>
    <div class="continent"><%= link_to "North America", posts_north_america_path %></div>
    <div class="continent"><%= link_to "Asia", posts_asia_path %></div>
    <div class="continent"><%= link_to "South America", posts_south_america_path %></div>
    <div class="continent"><%= link_to "Africa", posts_africa_path %></div>
    <div class="continent"><%= link_to "Antarctica", posts_antarctica_path %></div>
  </div>

  <div class="p-a-div">
    <% @posts.each do |p| %>
      <%= link_to user_post_path(@users, p) do %>
        <div class="p-a-entry-div">
          <div class="p-a-entry">
            <%= image_tag p.photo_one.url(:medium), class: 'p-a-photo-one' %>
              <%= image_tag p.photo_two.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_three.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_four.url(:medium), class: 'p-a-photo-234' %>
            <p class="p-a-city"><%= p.city %></p>
            <p class="p-a-country"><%= p.country %></p>
            <p class="p-a-rating"><%= p.rating %> / 5</p>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>

</body>

app/views/posts/index.html.erb
<head>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvQPK_z7tyIdBpGxui6Jps_zZsPudqzJ4"></script>

<script type="text/javascript">

mapStyle = [{"featureType":"all","elementType":"all","stylers":[{"hue":"#ff0000"},{"saturation":-100},{"lightness":-30}]},{"featureType":"all","elementType":"labels.text.fill","stylers":[{"color":"#ffffff"}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"color":"#353535"}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#656565"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"color":"#505050"}]},{"featureType":"poi","elementType":"geometry.stroke","stylers":[{"color":"#808080"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#454545"}]},{"featureType":"transit","elementType":"labels","stylers":[{"hue":"#000000"},{"saturation":100},{"lightness":-40},{"invert_lightness":true},{"gamma":1.5}]}]

function initialize() {
  var mapOptions = {
    center : {
        lat: 33.99163,
        lng: -118.46324
        },
    zoom: 3,
    styles: mapStyle
  };
  
  var map = new google.maps.Map(document.getElementById('postIndexMap'), mapOptions);
  var mapPoints = [<% @posts.each do |mp| %>
    {latitude: <%= mp.latitude %>, longitude: <%= mp.longitude %>},<% end %>];
  for(var i = 0; i < mapPoints.length; ++i)
  {
    var visitedLocation = new google.maps.LatLng(mapPoints[i].latitude, mapPoints[i].longitude);
    var marker = new google.maps.Marker({
      position: visitedLocation,
      title: 'city',
      map: map,
      draggable: false
    });
    //   google.maps.event.addListener(marker, 'click', function() {
    //     window.open('<%= link_to root_path %>');
    // });
  }
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>

</head>


<body>
  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>


  <div id="postIndexMap"></div>


  <div id="post-index-container">
      <% @posts.each do |p| %>
        <%= link_to user_post_path(@user, p) do %>
          <div class="posts-info-div">
            <%= image_tag p.photo_one.url(:medium) %>
            <p class="p-i-city-country"><%= p.city %>, <%= p.country %></p>
            <p class="p-i-rating">Rating: <%= p.rating %> / 5</p>
            <p class="p-i-days-ago"><%= ((Time.now.utc - p.created_at)/86400).floor %> days ago<p>
            <p><%= link_to "Edit Post", edit_user_post_path(@user, p) if p.user_id == current_user.id %>&nbsp&nbsp|&nbsp&nbsp<%= link_to "Delete Post", user_post_path(@user, p), method: :destroy if p.user_id == current_user.id %></p>
          </div>
        <% end %>
      <% end %>
  </div>
</body>

app/views/posts/north_america.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

  <div id="continent-list-div">
    <div class="continent"><%= link_to "All", posts_all_path %></div>
    <div class="continent"><%= link_to "Australia", posts_australia_path %></div>
    <div class="continent"><%= link_to "Europe", posts_europe_path %></div>
    <div class="continent-active"><%= link_to "North America", posts_north_america_path %></div>
    <div class="continent"><%= link_to "Asia", posts_asia_path %></div>
    <div class="continent"><%= link_to "South America", posts_south_america_path %></div>
    <div class="continent"><%= link_to "Africa", posts_africa_path %></div>
    <div class="continent"><%= link_to "Antarctica", posts_antarctica_path %></div>
  </div>

  <div class="p-a-div">
    <% @posts.each do |p| %>
      <%= link_to user_post_path(@users, p) do %>
        <div class="p-a-entry-div">
          <div class="p-a-entry">
            <%= image_tag p.photo_one.url(:medium), class: 'p-a-photo-one' %>
              <%= image_tag p.photo_two.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_three.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_four.url(:medium), class: 'p-a-photo-234' %>
            <p class="p-a-city"><%= p.city %></p>
            <p class="p-a-country"><%= p.country %></p>
            <p class="p-a-rating"><%= p.rating %> / 5</p>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>

</body>

app/views/posts/south_america.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

  <div id="continent-list-div">
    <div class="continent"><%= link_to "All", posts_all_path %></div>
    <div class="continent"><%= link_to "Australia", posts_australia_path %></div>
    <div class="continent"><%= link_to "Europe", posts_europe_path %></div>
    <div class="continent"><%= link_to "North America", posts_north_america_path %></div>
    <div class="continent"><%= link_to "Asia", posts_asia_path %></div>
    <div class="continent-active"><%= link_to "South America", posts_south_america_path %></div>
    <div class="continent"><%= link_to "Africa", posts_africa_path %></div>
    <div class="continent"><%= link_to "Antarctica", posts_antarctica_path %></div>
  </div>

  <div class="p-a-div">
    <% @posts.each do |p| %>
      <%= link_to user_post_path(@users, p) do %>
        <div class="p-a-entry-div">
          <div class="p-a-entry">
            <%= image_tag p.photo_one.url(:medium), class: 'p-a-photo-one' %>
              <%= image_tag p.photo_two.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_three.url(:medium), class: 'p-a-photo-234' %>
              <%= image_tag p.photo_four.url(:medium), class: 'p-a-photo-234' %>
            <p class="p-a-city"><%= p.city %></p>
            <p class="p-a-country"><%= p.country %></p>
            <p class="p-a-rating"><%= p.rating %> / 5</p>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>

</body>

app/views/users/edit.html.erb
<body>

  <div class="user-nav">
    <span><%= link_to "Dashboard", user_path(current_user) %></span>
      <span>|</span>
    <span><%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %></span>
  </div>

	<div class="col-lg-4 col-lg-offset-4" id="u-e-div">
		<%= form_for(@user, :html => {:multipart => true}) do |f| %>

			<div class="input-group-lg">
				First Name: <%= f.text_field :first, class: 'form-control' %>
			</div><br/>

			<div class="input-group-lg">
				Last Name: <%= f.text_field :last, class: 'form-control' %>
			</div><br/>

			<div class="input-group-lg">
				Email Address: <%= f.text_field :email, class: 'form-control' %>
			</div><br/>	

			<div class="input-group-lg">
				Profile Photo: <%= f.file_field :avatar, class: 'form-control' %>
			</div><br/>

			<%= f.submit "Submit", class: 'btn btn-lg u-e-submit' %>
		<% end %>
	</div>
</body>

app/views/users/show.html.erb
<html>
<head>

</head>


<body>
	
	<% if logged_in? %> 
		<div class="container">
		<div class="col-lg-12">
		<div class="panel panel-default">

		<div class="panel-heading u-s-panel-heading">
			<p class="u-s-title">Welcome, <%= current_user.first %>!</p>
			<p class="u-s-post-count">Entries Submitted: <span><%= @post_count %></span></p>
				<%= image_tag current_user.avatar.url(:small) %>
		</div>

		<br/>
		<div class="panel-body u-s-panel-body">
			<%= link_to "Create New Entry", new_user_post_path(@user), 'data-no-turbolink' => false %>
		</div>

		<div class="panel-body u-s-panel-body">
			<%= link_to "Manage Entries", user_posts_path(@user), 'data-no-turbolink' => false %>
		</div>

		<div class="panel-body u-s-panel-body">
			<%= link_to "- Browse Entry Collection -", posts_all_path %>
		</div>

		<div class="panel-body u-s-panel-body">
			<%= link_to "Update Personal Information", edit_user_path(@user) %>
		</div>

		<div class="panel-body u-s-panel-body">	
			<%= link_to "Log Out", logout_path, 'data-no-turbolink' => false %>
		</div><br/>
		</div>
		</div>
		</div>

	<% else %>
		<p style="color:white;font-size:40px;">You're logged out!</p>
		<%#= link_to "Log in", sessions_path %><br>
		<button style="height:100px; width:400px; font-size:35px;">
		<%= link_to "Return To Homepage", new_session_path %>
		</button>
	<% end %>

</body>

</html>


<%#= link_to "Add Current Lat/Lng to Database!", edit_user_path(current_user) %>

<%#= link_to "Send A Message!", new_message_path %>